version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      # Redis connection - dùng tên container
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD:-123123}
      # JWT Secret
      - JWT_SECRET=${JWT_SECRET:-b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACD/95aZ5eSSQZ+r9ffcdOwR3rW0Tyl0q4bgBXmpTI29JAAAAKDVkaK91ZGivQAAAAtzc2gtZWQyNTUxOQAAACD/95aZ5eSSQZ+r9ffcdOwR3rW0Tyl0q4bgBXmpTI29JAAAAEDglyZWnG1O9wXKqPfJaZDipAti8D1bZ2WPkboXB/caRf/3lpnl5JJBn6v199x07BHetbRPKXSrhuAFealMjb0kAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgMEBQYH}
    restart: unless-stopped
    networks:
      - homelab-network

# Dùng network đã có sẵn (chứa redis, postgres, auth-service)
networks:
  homelab-network:
    external: true