server:
  port: 8080

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: service_1_route
          uri: http://localhost:8081      # Khi chạy ở local máy bạn
          # uri: http://service1:8081    # Khi deploy lên Docker (sẽ đổi sau)
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1               # Bỏ chữ /service1 khi gửi đến service đích
            
  # Redis config for rate limiting (optional, configure when needed)
  data:
    redis:
      host: localhost
      port: 6379
      password: "123123"

jwt:
  secret: ${JWT_SECRET:b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACD/95aZ5eSSQZ+r9ffcdOwR3rW0Tyl0q4bgBXmpTI29JAAAAKDVkaK91ZGivQAAAAtzc2gtZWQyNTUxOQAAACD/95aZ5eSSQZ+r9ffcdOwR3rW0Tyl0q4bgBXmpTI29JAAAAEDglyZWnG1O9wXKqPfJaZDipAti8D1bZ2WPkboXB/caRf/3lpnl5JJBn6v199x07BHetbRPKXSrhuAFealMjb0kAAAAFnlvdXJfZW1haWxAZXhhbXBsZS5jb20BAgMEBQYH}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG